networks:
    dev:
        driver: bridge

services:
    ruga-password_manager-api-dev:
        image: docker.io/library/ruga-password_manager_image_dev:1.0.1
        depends_on:
            - ruga-password_manager-db-dev
        container_name: ruga-password_manager-services-dev
        ports:
            - "8080:80"
        build: 
            context: .
            dockerfile: Dockerfile
        environment:
            - ConnectionStrings__PostrgresqlConnection=User ID=POSTGRES_USER;Password=POSTGRES_PASSWORD;Server=ruga-password_manager-db-dev;Port=5432;Database=POSTGRES_DB;Pooling=true;
            - ASPNETCORE_URLS=http://+:80
        networks:
            - dev

    ruga-password_manager-db-dev:
        image: postgres:17.2-bookworm
        container_name: ruga-password_manager-db-dev
        environment:
            - POSTGRES_CONTAINER_USER=POSTGRES_USER
            - POSTGRES_CONTAINER_PASSWORD=POSTGRES_PASSWORD
            - POSTGRES_CONTAINER_DB=POSTGRES_DB
        ports:
            - "5433:5432"
        restart: always
        volumes:
            - app_data-volume:/var/lib/postgresql/data
        networks:
            - dev
volumes:
    app_data-volume: